edition = "2018"
max_width = 120

group_imports = "StdExternalCrate"
imports_granularity = "Module"

reorder_impl_items = true

unstable_features = true
use_small_heuristics = "Max"
use_field_init_shorthand = true
use_try_shorthand = true

format_macro_matchers = true
format_strings = true
match_block_trailing_comma = true
normalize_comments = true
newline_style = "Unix"

version = "Two"
